apiVersion: v1
kind: PersistentVolume
metadata:
  name: faiss-storage-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/tc-analyzer/faiss"
