apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: faiss-storage-pvc
  namespace: tc-analyzer
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
