apiVersion: v1
kind: Secret
metadata:
  name: tc-analyzer-secret
  namespace: tc-analyzer
type: Opaque
data:
  # Base64 encoded AWS credentials
  # Replace these with your actual base64-encoded AWS credentials
  # To encode: echo -n 'your-access-key' | base64
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  # Optional: AWS Session Token for temporary credentials
  # AWS_SESSION_TOKEN: <BASE64_ENCODED_SESSION_TOKEN>
---
# Example of how to create the secret with kubectl:
# kubectl create secret generic tc-analyzer-secret \
#   --from-literal=AWS_ACCESS_KEY_ID=your-access-key \
#   --from-literal=AWS_SECRET_ACCESS_KEY=your-secret-key \
#   --namespace=tc-analyzer
