[theme]
base = "dark"
primaryColor = "#00bcd4"             # Vibrant cyan accent
backgroundColor = "#0d0d0d"          # Deep black
secondaryBackgroundColor = "#1a1a1a" # Card contrast
textColor = "#f5f5f5"                # Soft white
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
