[theme]
base="dark"
primaryColor="#00bcd4"                # Vibrant cyan (modern accent)
backgroundColor="#0d0d0d"             # Deep black for immersive feel
secondaryBackgroundColor="#1a1a1a"    # Subtle contrast for panels/cards
textColor="#f5f5f5"                   # Softer white for readability
font="sans serif"                     # Clean and professional
